In [3]:
import sqlite3
import pandas as pd

In [15]:
conn = sqlite3.connect('/Users/akram/DataScienceProjects/customer-churn-prediction/data_warehouse/customers.db')

df = pd.read_sql_query("SELECT * FROM customers", conn)
df = df.drop(columns=['customerID'])

df.head()

,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,...,Churn,gender_Female,gender_Male,InternetService_DSL,InternetService_Fiber optic,InternetService_No,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,0.013889,0,1,0,2,0,0,...,0,1,0,1,0,0,0,0,1,0
1,0,0,0,0.472222,1,0,2,0,2,0,...,0,0,1,1,0,0,0,0,0,1
2,0,0,0,0.027778,1,0,2,2,0,0,...,1,0,1,1,0,0,0,0,0,1
3,0,0,0,0.625000,0,1,2,0,2,2,...,0,0,1,1,0,0,1,0,0,0
4,0,0,0,0.027778,1,0,0,0,0,0,...,1,1,0,0,1,0,0,0,1,0